spring:
  datasource:
    url: jdbc:mysql://localhost:3306/week5db # DB ??, ?? ??? ?? mydb ??? ??
    username: root # DB ????
    password: root # DB ????
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none # (create, update, validate, none ? ??)
    show-sql: true # ???? SQL? ??